[workspace]
channels = ["conda-forge"]
name = "esm-arpes-profile-collection"
platforms = ["linux-64"]
version = "2025.3.1"

[system-requirements]
libc = "2.17"

[feature.profile.dependencies]
bluesky-base = ">=1.14.4"
bluesky-queueserver = "*"
matplotlib-base= ">=3.9.3,<4"
networkx = ">=3.4.2,<4"
# nslsii = "==0.11.4"
numpy = "*"
ophyd = ">=1.11.0"
pyepics = "*"
python = ">=3.12,<3.13"
semver = ">=3.0.4,<4"
tiled-client = ">=0.1.6"
# needed until we get ophyd-async packaged
colorlog = ">=6.9.0,<7"
pydantic-numpy = "*"
hdf5-external-filter-plugins = ">=0.1.0,<0.2"
blosc-hdf5-plugin = ">=1.0.1,<2"
databroker = "==2.0.0b68"
p4p = ">=4.2.0,<5"
epicscorelibs = ">=7.0.7.99.1.1,<8"
bluesky-tiled-plugins = ">=2.0.0b68"
nexusformat = ">=2.0.0,<3"

[feature.profile.pypi-dependencies]
ophyd-async = { version = ">0.10.0", extras = ["ca", "pva"] }
nslsii = { git = "https://github.com/nmaytan/nslsii.git", rev = "78a2646" }


[feature.qs.dependencies]
bluesky-queueserver = "*"
bluesky-httpserver = "*"

[feature.qs.tasks]
# This section needs some development work to understand the best way to
# thread the required configuration through both the task and files checked into
# the profile.  These will interact with the ansible roles for pushing out the
# systemd units
qs-backend = "start-re-manager --profile-dir=."
qs-server = "uvicorn --host localhost --port 60610 bluesky_httpserver.server:app"


[feature.terminal.dependencies]
ipython = ">=9.5.0"
numpy = ">2"
pyqt = ">=5.15.11,<6"
pyqtgraph = ">=0.14.0,<0.15"

[feature.terminal.pypi-dependencies]
bsstudio = { git = "https://github.com/NSLS2/esm-bsstudio", rev = "master" }

[feature.terminal.tasks]
start = "unset SESSION_MANAGER && MPLBACKEND=Qt5Agg ipython --profile-dir=."
pvs = "ipython --profile-dir=. -c 'get_pv_types(); exit()'"

[feature.test.dependencies]
pytest = "*"

[feature.test.tasks]
tests = "pytest tests"
ipython = ">=9.5.0"

[environments]
terminal = {features=["profile", "terminal"], solve-group="profile"}
qs = {features=["profile", "qs"], solve-group="profile"}
test = {features=["profile", "test"], solve-group="profile"}

[dependencies]
python-confluent-kafka = ">=2.12.2,<3"
